version: "3.9"

services:
  database:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./:/app/
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user
    networks:
      - internal

  rabbitmq-container:
    image: rabbitmq:3.11-management
    hostname: rabbitmq-container
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - internal

  app:
    container_name: demo
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
      - rabbitmq-container
    volumes:
      - ./:/app/app
    links:
      - database
    networks:
      - internal
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/demo?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - spring_rabbitmq_host=rabbitmq-container
      - spring_rabbitmq_port=5672

networks:
  internal:
    name: internal